name: GitHub Release

on:
  push:
    branches:
      - main
      - github_action_workflow # TODO : remove this after try
    tags:
      - "v*"

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 45

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Copy CI gradle.properties
        run: mkdir -p ~/.gradle ; cp .github/ci-gradle.properties ~/.gradle/gradle.properties

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: 17

#      - name: Build app apk
#        id: buildApk
#        run: ./gradlew :app:assembleRelease

      - name: Build app bundle
        id: buildBundle
        run: ./gradlew :app:bundleRelease

#      - name: Upload app apk
#        uses: actions/upload-artifact@v3
#        id: app-apk
#        with:
#          name: app-release.apk
#          path: ${{ steps.buildApk.outputs }}

      - name: Upload app bundle
        uses: actions/upload-artifact@v3
        with:
          name: app-release.aab
          path: app/build/outputs/bundle/release/app-release.aab

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          generate_release_notes: true
          prerelease: false
          draft: false
          name: Release ${{ github.ref }}
          tag_name: ${{ github.ref }}
          files: |
            app/build/outputs/bundle/release/app-release.aab

      # TODO: See later
#      - name: Sign app bundle
#        uses: r0adkll/sign-android-release@v1
#        id: sign_app_bundle
#        with:
#          releaseDirectory: app/build/outputs/bundle/release
#          signingKeyBase64: ${{ secrets.KEY_STORE_BASE64 }}
#          alias: ${{ secrets.ALIAS }}
#          keyStorePassword: ${{ secrets.STORE_PASSWORD }}
#          keyPassword: ${{ secrets.KEY_PASSWORD }}
#        env:
#          BUILD_TOOLS_VERSION: "34.0.0"
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#
#      - name: Upload app bundle
#        uses: actions/upload-artifact@v3
#        with:
#          name: uploaded_app_sign_bundle
#          path: ${{ steps.sign_app_bundle.outputs.signedReleaseFile }}
#
#      - name: Publish to Play Store
#        uses: r0adkll/upload-google-play@v1
#        with:
#          serviceAccountJsonPlainText: ${{ secrets.SERVICE_JSON_ACCOUNT }}
#          packageName: com.bagnolati.learnoflegends
#          releaseFiles: app-release.aab
#          track: internal
#          status: draft


#  deploy:
#    needs: build
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v3
#
#      - name: Download app bundle from artifact
#        uses: actions/download-artifact@v3
#        with:
#          name: uploaded_app_sign_bundle
#
#      - name: Publish to Play Store
#        uses: r0adkll/upload-google-play@v1
#        with:
#          serviceAccountJsonPlainText: ${{ secrets.SERVICE_JSON_ACCOUNT }}
#          packageName: com.bagnolati.learnoflegends
#          releaseFiles: app-release.aab
#          track: internal
#          status: draft
